spring:
  datasource:
    url: jdbc:mysql://mysql:3306/wx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 317935q
  rabbitmq:
    host: rabbitmq # rabbitMQ的容器名称
    port: 5672
    username: guest
    password: guest
# 添加文件上传目录的配置
upload:
  dir: /root/wx/corn_leaf
# Flask Web服务地址
flask:
  url: http://python:5000/predict