spring:
  datasource:
    url: jdbc:mysql://mysql:3306/wx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 317935q
  rabbitmq:
    host: rabbitmq # rabbitMQ的容器名称
    port: 5672
    username: guest
    password: guest